[package]
name = "charming_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.101"

[dev-dependencies]
charming = { path = "../charming" }
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.11.0"
