name: Rust

on:
  push:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Building and testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  linting:
    name: Linting and formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

  msrv:
    name: MSRV checks
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: cargo install cargo-msrv
      - name: html
        if: always()
        run: cargo msrv verify --path charming --rust-version 1.66
      - name: ssr
        if: always()
        run: cargo msrv verify --path charming --rust-version 1.79 -- cargo check -F ssr
      - name: wasm
        if: always()
        run: cargo msrv verify --path charming --rust-version 1.78 --target wasm32-unknown-unknown -- cargo check -F wasm
